substitutions:
  ## Main prefix for all entities
  friendly_name: "Water Heater"
  ## Name of the node. Don't use underscores!
  ## https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
  node_name: "water-heater"

  ## SSID of your wifi
  wifi_ssid: !secret wifi_ssid
  ## Password of your wifi
  wifi_password: !secret wifi_password
  ## Password for fallback wifi hotspot
  wifi_ap_password: !secret wifi_ap_password

  ## UART configuration. Somtimes may need to swap tx/rx.
  tx_pin: GPIO19 # use TX for iot-uni-dongle or coolrf-heatstick
  rx_pin: GPIO20 # use RX for iot-uni-dongle or coolrf-heatstick

## Please do not change packages order it is very important, just comment/uncomment
packages:
  remote:
    url: https://github.com/dentra/esphome-ewh
    ref: master # cant use substitutions here
    files:
      ## Enable additional WiFi signal sensor. Comment next line to disable.
      - packages/wifi_signal.yaml
      ## Enable additional Uptime sensor. Comment next line to disable.
      - packages/uptime.yaml
      ## Uncomment next line to enable additional restart button.
      - packages/restart.yaml
      ## optional package, uncomment next line to enable experimental cloud support
      # - packages/cloud.yaml
      # Required package, do not comment
      - packages/base.yaml
      # Required package, replace with esp8266.yaml if you use ESP8266
      - packages/esp32.yaml

## Enable Home Assistant API connection. Please comment if you plan to use MQTT.
api:

## Uncomment to enable MQTT connecion.
# mqtt:
#   broker: !secret mqtt_borker
#   username: !secret mqtt_username
#   password: !secret mqtt_password

# WiFi hotspot configuration.
# Comment next 3 lines to enable manual WiFi conviguration via access point.
wifi:
  ssid: $wifi_ssid
  password: $wifi_password

uart:
  - tx_pin: $tx_pin
    rx_pin: $rx_pin
    baud_rate: 9600

vport:
  - platform: bwh

climate:
  - platform: bwh
    id: whc
    name: Climate

## Uncomment to enable cloud support
# rka_cloud:
#   id: cloud
#   mac: !secret cloud_mac
#   uid: !secret cloud_uid

## Uncomment to enable web server
# web_server:
#   include_internal: true

