substitutions:
  ## Main prefix for all entities
  friendly_name: "Thermostat"
  ## Name of the node. Don't use underscores!
  ## https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
  node_name: "thermostat"

  ## SSID of your wifi
  wifi_ssid: !secret wifi_ssid
  ## Password of your wifi
  wifi_password: !secret wifi_password
  ## Password for fallback wifi hotspot
  wifi_ap_password: !secret wifi_ap_password

  ## UART configuration. Sometimes may need to swap tx/rx.
  tx_pin: GPIO19 # use TX for iot-uni-dongle or coolrf-heatstick
  rx_pin: GPIO20 # use RX for iot-uni-dongle or coolrf-heatstick

  ## TODO remove on release
  project_source_refresh: 600s

## please do not change packages order it is very important, just comment/uncomment
packages:
  remote:
    url: https://github.com/dentra/esphome-ewh
    ref: master # cant use substitutions here
    files:
      ## Enable additional WiFi signal sensor. Comment next line to disable.
      - packages/wifi_signal.yaml
      ## Enable additional Uptime sensor. Comment next line to disable.
      - packages/uptime.yaml
      ## Uncomment next line to enable additional restart button.
      - packages/restart.yaml
      # Required package, do not comment move or remove
      - packages/base.yaml
      # Required package, replace with esp32.yaml/esp8266.yaml if you use ESP32/ESP8266
      - packages/esp8266.yaml

## Enable Home Assistant API connection. Please comment if you plan to use MQTT.
api:

## Uncomment to enable MQTT connection.
# mqtt:
#   broker: !secret mqtt_borker
#   username: !secret mqtt_username
#   password: !secret mqtt_password

wifi:
  ssid: $wifi_ssid
  password: $wifi_password

## Configure hardware serial port
uart:
  - tx_pin: TX
    rx_pin: RX
    baud_rate: 9600

## Configure virtual port
vport:
  - platform: ets

## Configure API
# ets:
#   on_state:
#     then:
#       lambda: |-
#         // do some stuff

## Configure climate component
climate:
  - platform: ets
    name: Climate
    floor_temperature:
      name: Floor Temperature

## Uncomment to enable cloud support
# rka_cloud:
#   id: cloud
#   mac: !secret cloud_mac_ets
#   uid: !secret cloud_uid_ets

## Uncomment to enable web server
# web_server:
#   include_internal: true
