substitutions:
  # main prefix for all entities
  friendly_name: "Water Heater"
  # name of your node
  node_name: "water-heater"
  # use "esp32-s3-devkitc-1" for Lilygo T-Dongle S3, "esp12e" for iot-uni-dongle,
  # "esp8285" for coolrf-heatstick, or your own if you know it
  board: "esp32-s3-devkitc-1"
  # time platform: "sntp" or "homeassistant"
  time_platform: "sntp"
  # SSID of your wifi
  wifi_ssid: !secret wifi_ssid
  # password of your wifi
  wifi_password: !secret wifi_password
  # password for fallback wifi hotspot
  wifi_ap_password: !secret wifi_ap_password
  # UART configuration.
  tx_pin: GPIO19 # use TX for iot-uni-dongle or coolrf-heatstick
  rx_pin: GPIO20 # use RX for iot-uni-dongle or coolrf-heatstick

# please do not change packeages order it is very important, just comment/uncomment
packages:
  remote:
    url: https://github.com/dentra/esphome-ewh
    ref: master # cant use substitutions here
    files:
      ## Enable additional WiFi signal sensor. Comment next line to disable.
      - packages/wifi_signal.yaml
      ## Enable additional Uptime sensor. Comment next line to disable.
      - packages/uptime.yaml
      ## Uncomment next line to enable additional restart button.
      - packages/restart.yaml
      ## Uncomment next line to enable additional diagnostic clock sensor
      # - packages/clock.yaml
      ## Uncomment next line to enable additional diagnostic timer sensor
      # - packages/timer.yaml
      ## Uncomment next line to enable standalone web ui
      # - packages/ewh_web.yaml
      ## optional package, uncomment next line to enable experimental cloud support
      # - packages/cloud.yaml
      # Required package, do not comment move or remove
      - packages/base.yaml
      # Required package, replace with esp32.yaml/esp8266.yaml if you use ESP32/ESP8266
      - packages/esp32_s3.yaml

time:
  platform: sntp

# Enable Home Assistant API connection.
api:

# Uncomment to enable MQTT connecion.
# mqtt:
#   broker: !secret mqtt_borker
#   username: !secret mqtt_username
#   password: !secret mqtt_password

# WiFi hotspot configuration.
# Comment next 3 lines to enable manual WiFi conviguration via access point.
wifi:
  ssid: $wifi_ssid
  password: $wifi_password

uart:
  tx_pin: $tx_pin
  rx_pin: $rx_pin
  baud_rate: 9600

vport:
  - platform: ewh

climate:
  - platform: ewh
    id: whc
    name: None # use friendly_name
    # Optional, Bacteria Stop Technology switch
    bst:
      name: "BST"
## Uncomment to enable and override cloud support
# rka_cloud:
#   id: cloud
#   mac: !secret cloud_mac
#   uid: !secret cloud_uid

