substitutions:
  ## Main prefix for all entities
  friendly_name: "Water Heater"
  ## Name of the node. Don't use underscores!
  ## https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
  node_name: "water-heater"

  ## time platform: "sntp" for MQTT or "homeassistant" for API
  time_platform: "homeassistant"

  ## SSID of your wifi
  wifi_ssid: !secret wifi_ssid
  ## Password of your wifi
  wifi_password: !secret wifi_password
  ## Password for fallback wifi hotspot
  wifi_ap_password: !secret wifi_ap_password

  ## UART configuration.
  tx_pin: GPIO19 # use TX for iot-uni-dongle or coolrf-heatstick
  rx_pin: GPIO20 # use RX for iot-uni-dongle or coolrf-heatstick

## Please do not change packages order it is very important, just comment/uncomment
packages:
  remote:
    url: https://github.com/dentra/esphome-ewh
    ref: master # cant use substitutions here
    files:
      ## Enable additional WiFi signal sensor. Comment next line to disable.
      - packages/wifi_signal.yaml
      ## Enable additional Uptime sensor. Comment next line to disable.
      - packages/uptime.yaml
      ## Uncomment next line to enable additional restart button.
      - packages/restart.yaml
      ## Uncomment next line to enable additional diagnostic clock sensor
      # - packages/clock.yaml
      ## Uncomment next line to enable additional diagnostic timer sensor
      # - packages/timer.yaml
      ## Uncomment next line to enable standalone web ui
      # - packages/ewh_web.yaml
      ## optional package, uncomment next line to enable experimental cloud support
      # - packages/cloud.yaml
      # Required package, do not comment move or remove
      - packages/base.yaml
      # Required package, replace with esp32.yaml/esp8266.yaml if you use ESP32/ESP8266
      - packages/esp32_s3.yaml

## Enable Home Assistant API connection. Please comment if you plan to use MQTT.
api:

## Uncomment to enable MQTT connection.
# mqtt:
#   broker: !secret mqtt_borker
#   username: !secret mqtt_username
#   password: !secret mqtt_password

# WiFi hotspot configuration.
# Comment next 3 lines to enable manual WiFi configuration via access point.
wifi:
  ssid: $wifi_ssid
  password: $wifi_password

time:
  - platform: $time_platform

uart:
  - tx_pin: $tx_pin
    rx_pin: $rx_pin
    baud_rate: 9600

vport:
  - platform: ewh

climate:
  - platform: ewh
    id: whc
    name: Climate
    # Optional, Bacteria Stop Technology switch
    bst:
      name: "BST"

## Uncomment to enable and override cloud support
# rka_cloud:
#   id: cloud
#   mac: !secret cloud_mac
#   uid: !secret cloud_uid

