name: ci

on:
  push:
    branches: [master]

env:
  ESPHOME_VERSION: "2024.12.4"
  PYTHON_VERSION: "3.12"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      firmware-path: ${{ steps.esphome.outputs.firmware-path }}
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        component:
          - ewh
          - bwh
          - ets
          - ehu
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Generate fake secrets.yaml
        run: |
          touch secrets.yaml
          echo "wifi_ssid: 'fake_ssid'" >> secrets.yaml
          echo "wifi_password: '12345678'" >> secrets.yaml
          echo "wifi_ap_password: '12345678'" >> secrets.yaml
      - name: Build project
        uses: dentra/esphome-action@main
        id: esphome
        with:
          version: ${{ env.ESPHOME_VERSION }}
          config: ${{ matrix.component }}.yaml
          substitutions: '{"project_version": "dev", "project_name": "${{ matrix.component }}"}'
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Show firmware artifacts
        run: |
          ls -l ${{ steps.esphome.outputs.firmware-path }}/firmware.*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.component }}-dev-${{ github.run_id }}.zip
          path: |
            ${{ steps.esphome.outputs.firmware-path }}/firmware.*
            !${{ steps.esphome.outputs.firmware-path }}/firmware.bin
          retention-days: 3
          if-no-files-found: error
